version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install telebot
            pip install flask
      - run:
          name: Give execution permission to bgmi
          command: chmod +x bgmi
      - run:
          name: Run the Python script
          command: python N.py
      - run:
          name: Run bgmi binary file
          command: ./bgmi
