version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
      - run:
          name: Give execution permission to bgmi
          command: chmod +x *
      - run:
          name: Run the Python script
          command: python LEGEND.py
      - run:
          name: Run LEGEND binary file
          command: ./LEGEND
